/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Choice;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-31T12:55:18.203Z")

@Api(value = "votes", description = "the votes API")
@RequestMapping(value = "/Alex57x/Projet/1.0.0")
public interface VotesApi {

    @ApiOperation(value = "Participer à un sondage", nickname = "postVote", notes = "Participation de l'utilisateur", response = Choice.class, tags = {"votes",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Opération réussie", response = Choice.class),
            @ApiResponse(code = 400, message = "Manque des informations dans le corps."),
            @ApiResponse(code = 404, message = "Ressource introuvable"),
            @ApiResponse(code = 409, message = "Certaines informations ne respectent pas les conditions."),
            @ApiResponse(code = 500, message = "Echec de connexion à la base de données.")})
    @RequestMapping(value = "/votes/{surveyID}/{choiceID}",
            produces = {"application/json"},
            method = RequestMethod.PATCH)
    ResponseEntity<Choice> postVote(@ApiParam(value = "ID du sondage pour lequel on souhaite avoir des statistiques", required = true) @PathVariable("surveyID") Long surveyID, @ApiParam(value = "ID du choix de la date", required = true) @PathVariable("choiceID") Long choiceID, @ApiParam(value = "Choix de l'utilisateur", required = true) @Valid @RequestBody Choice choice);

}
