image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - 'mvn package'
  only:
    - master
  artifacts:
    paths:
      - ./target/swagger-spring-*.jar

sonarqube:
  stage: test
  except:
    - master
  script:
    - 'mvn build sonar:sonar'

test:
  stage: test
  script:
    - 'mvn test'
  only:
    - merge_requests