image: maven:latest

build:
  stage: build
  script:
    - 'mvn package'
  only:
    - master
  artifacts:
    paths:
      - ./target/swagger-spring-*.jar
      
test:
  stage: test
  script:
    - 'mvn test'
  only:
    - merge_requests